# docker-compose.yml
# Ruby, PostgreSQL, MongoDB, Redis, Sidekiq, Pry

version: "3.7"
services:
    app:
        image: app:dev
        container_name: app
        build:
            context: ./app
#            network: host
            args:
                SOURCE_PATH: ${SOURCE_PATH}
                BUNDLE_PATH: ${STORAGE_PATH}/bundle
                RUBY_DOWNLOAD_URL: ${RUBY_DOWNLOAD_URL}
                RUBY_DOWNLOAD_SHA256: ${RUBY_DOWNLOAD_SHA256}
        network_mode: "host"        
#        networks:
#            - app_network
        ports:
            - "3000:3000"
        volumes:
            - ${PROJECT_SOURCE}:${SOURCE_PATH}
            - app_storage:${STORAGE_PATH}
        working_dir: ${SOURCE_PATH}
        stdin_open: true
        tty: true            

#    app_storage:
#        image: busybox
#        volumes:
#            - ${STORAGE_PATH}
    
    postgres:
        build:
            context: ./postgres
#            network: host
        network_mode: "host"        
#        networks:
#            - app_network
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
       
    redis:
        image: redis:4.0-alpine
        command: [redis-server]
#        networks:
#            - app_network
        network_mode: "host"        
        ports:
            - "6379:6379"
#        build:
#            context: .
#            network: host
        volumes:
            - redis:/var/lib/redis/data

    mongo:
        image: mongo:4.1-bionic
#        networks:
#            - app_network
        network_mode: "host"        
        ports:
            - "27017:27017"
#        build:
#            context: .
#            network: host
        volumes:
            - mongo:/data/db

#networks:
#    app_network:

volumes:
    app_storage:
    postgres:
    redis:
    mongo:

