# docker-compose.yml
# Ruby, PostgreSQL, MongoDB, Redis, Sidekiq, Pry

version: "3.7"
services:
    app:
        image: app:dev
        container_name: app
        build:
            context: ./app
            args:
                HOST_USER: ${HOST_USER}
                SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
                BUNDLE_PATH: ${STORAGE_PATH}/bundle
                RUBY_DOWNLOAD_URL: ${RUBY_DOWNLOAD_URL}
                RUBY_DOWNLOAD_SHA256: ${RUBY_DOWNLOAD_SHA256}
        networks:
            - app_network
        ports:
            - "3000:3000"
        volumes:
            - ${HOST_SOURCE_PATH}:${SOURCE_PATH}
            - app_path:${APP_PATH}
            - app_storage:${STORAGE_PATH}
        stdin_open: true
        tty: true 
        working_dir: ${APP_PATH}

    postgres:
        build:
            context: ./postgres
        network_mode: "service:app"        
        volumes:
            - postgres:/var/lib/postgresql/data
       
    redis:
        image: redis:4.0-alpine
        command: [redis-server]
        network_mode: "service:app"        
        volumes:
            - redis:/var/lib/redis/data

    mongo:
        image: mongo:4.1-bionic
        network_mode: "service:app"        
        volumes:
            - mongo:/data/db

networks:
    app_network:

volumes:
    app_path:    
    app_storage:
    postgres:
    redis:
    mongo:
