version: "3.7"
services:
    ruby:
        build: ./ruby-2.5.3/
        image: ruby-2.5.3
        environment:
            RACK_ENV: development        

    postgres:
        build: ./postgres-10/
        image: postgres-10
        ports:
        - '5432:5432'
        volumes:
        - postgres:/var/lib/postgresql/data
        env_file:
        - '.env'
       
    redis:
        image: redis:4.0-alpine
        command: [redis-server]
        ports:
        - '6379:6379'
        volumes:
        - redis:/var/lib/redis/data
        env_file:
        - '.env'

    mongo:
        image: mongo:3.6
        ports:
        - '27017:27107'
        volumes:
        - mongo:/data/db
        env_file:
        - '.env'

volumes:
  postgres:
  redis:
  mongo:
  
