# docker-compose.yml
# Ruby, Rails, PostgreSQL, MongoDB, Redis, Sidekiq, Pry

version: "2"
services:

    app:
        build: ./app/
        image: app:dev
        ports:
            - 3000:3000
        volumes:
            - 'c:/projects/ruby/athena/:/app'
        volumes_from:
            - bundle
        working_dir: /app    
        environment:
            BUNDLE_PATH: '/bundle'
        links:
            - postgres
            - redis
            - mongo
        stdin_open: true
        tty: true            

    bundle:
        image: busybox
        volumes:
            - /bundle
    
    postgres:
        build: ./postgres/
        image: postgres:dev
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - '.env'
       
    redis:
        image: redis:4.0-alpine
        command: [redis-server]
        volumes:
            - redis:/var/lib/redis/data
        env_file:
            - '.env'

    mongo:
        image: mongo:3.6
        volumes:
            - mongo:/data/db
        env_file:
            - '.env'

volumes:
  postgres:
  redis:
  mongo:
  
