# docker-compose.yml
# Ruby, Rails, PostgreSQL, MongoDB, Redis, Sidekiq, Pry

version: "3.7"
services:

    app:
        build: ./app/
        image: app
        ports:
            - 3000:3000
        volumes:
            - 'c:/projects/ruby/athena/:/app'
        environment:
            RACK_ENV: development        
        links:
            - postgres
            - redis
            - mongo
        stdin_open: true
        tty: true            
        
    postgres:
        build: ./postgres/
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - '.env'
       
    redis:
        image: redis:4.0-alpine
        command: [redis-server]
        ports:
            - 6379:6379
        volumes:
            - redis:/var/lib/redis/data
        env_file:
            - '.env'

    mongo:
        image: mongo:3.6
        ports:
            - 27017:27107
        volumes:
            - mongo:/data/db
        env_file:
            - '.env'

volumes:
  postgres:
  redis:
  mongo:
  
